#!/bin/bash

if [[ -n $RESRC_BASE_VERSION ]]
then
    RESRC_BASE_README="$(cat "${RESRC_BASE_PROFIL_DOSSIER}/ressources/README.md")"
    RESRC_BASE_profil "resrc-base"
    
    RESRC_BASE_copier "profil"
    mkdir "${RESRC_BASE_PROJET_DOSSIER}/ressources"

    RESRC_BASE_configurer "profil"
fi